### ISSUE TITLE
Can multiple be supported？

### ISSUE THREAD

**Issue by seepine** [vishnubob/wait-for-it#116]
for example
```
wait-for-it.sh --strict google.com:80 github.com:80 -- echo "google and github is up"
```

and google err or github err ,  will not execute

**Comment by daveteu** [comment]
because the syntax is as follows

```
wait-for-it.sh <server:port> -- <next command>
```

You can actually nest the commands

```
wait-for-it.sh --strict google.com:80 -- wait-for-it.sh --strict GitHub.com:80 -- echo google and github is up
```

**Comment by roerohan** [comment]
@daveteu I think your solution isn't waiting for "multiple" ports to be up. It first wats for `google.com:80` and then after that waits for `github.com:80`. Ideally, it should wait for both in parallel, and not one after another. But of course, it serves the usecase.

However, @seepine, in case you want the service to wait for both ports in parallel, I've implemented a binary executable version for `wait-for-it` in golang, you can take a look [here](https://github.com/roerohan/wait-for-it).

**Comment by atkrad** [comment]
Hey @seepine, @daveteu 

You can use the [Wait4X](https://github.com/atkrad/wait4x), It's already supported multiple host checking.

Example:
wait4x tcp 1.1.1.1:80 1.1.1.1:53 --log-level debug

**Comment by seepine** [comment]
Maybe this is simple.

Touch wait.sh
```shell
#!/bin/bash

wait=$WAIT_FOR
echo 'Read WAIT_FOR' $wait
echo 'Read WAIT_TIMEOUT' $WAIT_TIMEOUT

arr=${WAIT_FOR//,/ }

for each in $arr
do
 code=`wait-for-it.sh -t $WAIT_TIMEOUT --strict --quiet $each -- echo "ok"`
 if [[ $code == "ok" ]]
 then
    echo $each' is ok'
 else
    exit 1
 fi
done

exit 0
```

### Use in shell
and export the env
```shell
export WAIT_FOR=172.18.46.233:3306,172.18.46.233:6379
```

Then run
```shell
wait.sh
```

### Use in docker
build docker image
```dockerfile
FROM apline

copy wait-for-it.sh /usr/local/bin/wait-for-it.sh
copy wait.sh /usr/local/bin/wait.sh

# ...

CMD wait.sh && java -jar demo.jar
```

run docker
```shell
docker run -e WAIT_FOR=172.18.46.233:3306,172.18.46.233:6379 demo:latest
```
