### ISSUE TITLE
Can you please explain to me when I need to use this project?

### ISSUE THREAD

**Issue by sekmo** [vishnubob/wait-for-it#119]
Could you explain to me why should I use this project?
Is it not enough to use the `depends_on` directive with `condition: service_healthy` in docker-compose.yml?

**Comment by gioamato** [comment]
Correct about Docker, you should be ok with `depends_on` in most cases.

But it is out of scope in Kubernetes for example, there isn't an equivalent for `depends_on`. Your application should be responsible for connections logic.

E.g.: with a `wait-for-it` layer in your dockerfiles you can dev in Docker and deploy the same app on K8s in production.

**Comment by sekmo** [comment]
Oh, I see, grazie! Thanks for the (super fast) response!
