### ISSUE TITLE
Not compatible with mac?

### ISSUE THREAD

**Issue by chrismichaels84** [vishnubob/wait-for-it#13]
Trying all the examples in iTerm2 on my mac, I get the following error:

```bash
$ wait-for-it.sh www.google.com:80 -- echo "google is up"
wait-for-it.sh: line 53: timeout: command not found
wait-for-it.sh: timeout occurred after waiting 15 seconds for www.google.com:80
google is up
```

I've tried with variations such as using `bash` and `sh` and different working directories. Is this just not compatible with mac osx, El Captain?

**Comment by nwinkler** [comment]
The `timeout` command is not available on Mac OS X by default. There's a discussion with some possible alternatives here: http://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x

**Comment by chrismichaels84** [comment]
Thank you. that worked for me.

**Comment by ryandav** [comment]
If you are looking for a wait-for-it script that avoids timeout so that it works on a mac, I've written a simple version uploaded here:
https://github.com/ryandav/wait-for-it-mac
