### ISSUE TITLE
Volunteer Needed

### ISSUE THREAD

**Issue by vishnubob** [vishnubob/wait-for-it#21]
Hi there! I wrote wait-for-it in order to help me orchestrate containers I operate at my day job. I thought it was a neat little script, so I published it. I assumed I would be its only user, but that's not what happened! wait-for-it has received more stars then all of my other public repositories put together. I had no idea this tool would solicit such an audience, and I was equally unprepared to carve out the time required to address my user's issues and patches.  I would like to solicit a volunteer from the community who would be willing to be a co-maintainer of this repository. If this is something you might be interested in, please email me at waitforit@polymerase.org. Thanks!

**Comment by steenzout** [comment]
@vishnubob I'm not a bash expert but I can help. let me know.

**Comment by eigood** [comment]
Hmm.  Very hmm.  I'm interested in helping with this.  We've recently starting making use of docker-compose at work, after having used docker for the last year.

As a pedigree, I guess I should mention "shoop".  SHell Object-Oriented Programming.  Going to http://shoop.sourceforge.net, then looking at the code repo(in CVS), should give you quite a jolt.  It is a tiny bit orphaned, but was written to run in ash, dash, bash, and ksh.

**Comment by mauricionr** [comment]
:+1:
