### ISSUE TITLE
Environment variables like PORT, HOST, and TIMEOUT clobbered

### ISSUE THREAD

**Issue by doublemarked** [vishnubob/wait-for-it#23]
The script contaminates the environment, clobbering the `PORT` env-var, among others. These are not-uncommon names to use when setting up services in a container.

It might be wise for the script to namespace its env-vars, like `WAITFORIT_PORT`

**Comment by RobinClowers** [comment]
Alternatively, you could use local variables.

**Comment by douglas-gibbons** [comment]
Thanks @doublemarked  - now fixed with #44
