### ISSUE TITLE
single quotes getting removed from the command args

### ISSUE THREAD

**Issue by indicalabs** [vishnubob/wait-for-it#39]
I am trying to run nginx startup command in the command args but failing

```
bash-4.3# /tmp/wait-for-fpm.sh webapp:9000 -t 100 -- nginx -g 'daemon off;'
wait-for-fpm.sh: waiting 100 seconds for webapp:9000
wait-for-fpm.sh: webapp:9000 is available after 0 seconds
nginx -g daemon off;
nginx: invalid option: "off;"
bash-4.3# 

```
Can't find how the signgle quotes getting removed 
The command should be as it is like `nginx -g 'daemon off;'` not `nginx -g daemon off;`

**Comment by szczad** [comment]
Have a look at current pull requests. i.e.:
https://github.com/vishnubob/wait-for-it/pull/40

**Comment by douglas-gibbons** [comment]
Fix now merged in to master. Thanks!
