### ISSUE TITLE
Busybox's timeout requires different arguments

### ISSUE THREAD

**Issue by iturgeon** [vishnubob/wait-for-it#5]
I was using wait-for-it on a debian docker container, and all things were great (thanks for the script!).

However, we switched to an Alpine Linux based docker image (which uses busybox) and the script stopped waiting correctly.

As it turns out `timeout` requires an argument flag for the time.  Here's the manual from https://busybox.net/downloads/BusyBox.html

> timeout
> timeout [-t SECS] [-s SIG] PROG [ARGS]
> Runs PROG. Sends SIG to it if it is not gone in SECS seconds. Defaults: SECS: 10, SIG: TERM.

This differs from typical linux usage:

> timeout [OPTION] DURATION COMMAND [ARG]...

Changing lines 52 and 54 where `timeout` is used by prepending `-t` before the `$TIMEOUT` causes it to work.

Here's the working result: 

``` bash
wait_for_wrapper()
{
    # In order to support SIGINT during timeout: http://unix.stackexchange.com/a/57692
    if [[ $QUIET -eq 1 ]]; then
        timeout -t $TIMEOUT $0 --quiet --child --host=$HOST --port=$PORT --timeout=$TIMEOUT &
    else
        timeout -t $TIMEOUT $0 --child --host=$HOST --port=$PORT --timeout=$TIMEOUT &
    fi
    PID=$!
    trap "kill -INT -$PID" INT
    wait $PID
    RESULT=$?
    if [[ $RESULT -ne 0 ]]; then
        echoerr "$cmdname: timeout occurred after waiting $TIMEOUT seconds for $HOST:$PORT"
    fi
    return $RESULT
}
```

I did a quick search for a simple method to determine if busybox is being used, not sure what the best solution would be.  Worst case - this post may help others in a similar situation.

**Comment by vishnubob** [comment]
While I like the idea of simultaneously supporting busybox, the problem is that busybox doesn't seem to support the [/dev/tcp](http://www.tldp.org/LDP/abs/html/devref1.html#DEVTCP) extension that is built into bash, which is an intrinsic requirement of `wait-for-it`.  If you have different information, please let me know.

**Comment by iturgeon** [comment]
Perhaps `netcat` could substitute? 

`nc -z $HOST $PORT` seems like it's behaving similarly to `/dev/tcp`.  nc appears to be part of busy box too.  Though I don't really know the implications of switching or falling back

**Comment by iturgeon** [comment]
Also of note in this case, `echoerr "$cmdname: timeout occurred after waiting $TIMEOUT seconds for $HOST:$PORT"` is executed immediately after `timeout` fails with a status code of 127.

I'm wondering if it might be preferable that the script just waits the maximum time?

**Comment by vishnubob** [comment]
If you are interested in adding support for busybox, please feel free to fork this repository and adjust it to your needs.  If your modifications provide simultaneous compatibility with bash, I would welcome a pull request.

**Comment by Vanuan** [comment]
@vishnubob have you looked into #6 yet?

**Comment by mahnunchik** [comment]
+1

**Comment by tompluess** [comment]
#31 fixes the call to `timeout` on busybox while not breaking the the call to `timeout` on debian.

**Comment by douglas-gibbons** [comment]
Busybox support added with [this pull request](https://github.com/vishnubob/wait-for-it/pull/6). Note that this does require bash to be installed on busybox.

**Comment by davidghiurco** [comment]
@iturgeon Thanks for posting this!! Helped me figure out why timeout was not working when switching from a fat ubuntu docker image to alpine.

**Comment by socketpair** [comment]
See https://github.com/mirror/busybox/commit/c9720a761e88e83265b4d75808533cdfbc66075b

LOL, Busybox has fixed that. Newer busybox will not wok with workaround made for old one (!)
