### ISSUE TITLE
Not working for cassandra docker container

### ISSUE THREAD

**Issue by supritshah1289** [vishnubob/wait-for-it#62]
<img width="1273" alt="screen shot 2018-10-24 at 9 23 37 pm" src="https://user-images.githubusercontent.com/5491337/47470336-504b8d00-d7d3-11e8-9c17-084f278cc83f.png">

Eventhough the docker cassandra container is running. I am manually testing the script on running container. However, its still printing db is up. For host I have also tried name of the container:port. I am getting same error results for that input as well

Thank you

**Comment by aviau** [comment]
> Cassandra container is running

> its still printing db is up

This is how it works, yes.
