### ISSUE TITLE
Prefix http:// does not work

### ISSUE THREAD

**Issue by adr-arroyo** [vishnubob/wait-for-it#74]
When a preffix is used before the domain or IP, like http://localhost:8080, the script recognizes the preffix as the domain so it tries to ping without the port, like:

```
wait-for-it.sh: waiting 10 seconds for http://localhost
wait-for-it.sh: timeout occurred after waiting 10 seconds for http://localhost
```

**Comment by garethrandall** [comment]
I think you should not use the http:// prefix, since the script connects to a raw IP address and port number and does not care whether it is http, https, mysql (for example) or any other protocol that is on that port.

So just use:
`localhost:8080`

**Comment by adr-arroyo** [comment]
Sorry I fixed this and forgot to close the issue!

Thanks for the reply!
