### ISSUE TITLE
How to wait for multiple ports to be ready?

### ISSUE THREAD

**Issue by gkotian** [vishnubob/wait-for-it#99]
Having quickly skimmed through the script, I couldn't find a way to wait for multiple host+port combinations to be ready. Any pointers on the best way to do this?
One way I can imagine is one `wait-for-it` starting another `wait-for-it`.

This is probably not a common situation, but in my case I need to wait for two independent databases to get ready before launching my app.

**Comment by deiga** [comment]
Could `wait` work for your case?

```
wait-for-it.sh foo &
wait-for-it.sh bar &
wait-for-it.sh baz &

wait
```

**Comment by gkotian** [comment]
That's a good idea. I'll give it a shot.

**Comment by gkotian** [comment]
I'm sorry that I haven't been able to test this out yet. I will close this issue for now, and reopen if necessary whenever I manage to start looking into this again.
